//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class libros
    {
        public decimal ID { get; set; }
        public string titulo { get; set; }
        public string genero { get; set; }
        public string estado { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public string autor { get; set; }
        public Nullable<System.DateTime> fechaPublicacion { get; set; }
        public string imagen { get; set; }
    }
}
