//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public decimal ID { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public string correo { get; set; }
        public string contrasenia { get; set; }
        public Nullable<decimal> ID_rol { get; set; }
        public byte[] fechaRegistro { get; set; }
    
        public virtual roles roles { get; set; }
    }
}
